import { useEffect } from "react";
import { Inter } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "./scss/styles.scss";
import "./scss/index.scss";
import "./scss/intro.scss";
import "./scss/hub.scss";
import "./scss/home.scss";
import "./scss/pro5.scss";
import "./scss/setting.scss";
import TopNav from "./Component/header";
import Footer from "./Component/footer";
import { TranslationProvider } from "./Component/TranslationProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  useEffect(() => {
    // Ensure that Bootstrap's JavaScript (if used) works correctly
    if (typeof window !== "undefined") {
      require("bootstrap/dist/js/bootstrap.bundle.min.js");
    }
  }, []);

  return (
    <html lang={locale || "en"}>
      <body className={inter.className}>
        <TranslationProvider locale={locale} namespaces={['footer', 'topnav', 'profile+setting']}>
          <TopNav />
          {children}
          <Footer />
        </TranslationProvider>
      </body>
    </html>
  );
}

